# Generated by Django 3.2.9 on 2021-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalfaqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('your_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('your_phone', models.CharField(max_length=100)),
                ('your_email', models.CharField(max_length=100)),
                ('your_address', models.CharField(max_length=100)),
                ('Choose_your_slot', models.CharField(max_length=100)),
                ('Choose_day', models.CharField(max_length=100)),
                ('Choose_Doctor', models.CharField(max_length=100)),
                ('Type_of_service', models.CharField(max_length=100)),
            ],
        ),
    ]
